Fcbn\NewSIFloreBundle\Entity\MapLayers:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

        treeNodeChild:
            type: string
            length: 255
            column: tree_node_child

        label:
            type: string
            length: 255

        variableJavascript:
            type: string
            length: 255
            column: variable_javascript

        layers:
            type: string
            length: 255

        typeWebservice:
            type: string
            length: 255
            column: type_webservice
        zone:
            type: string
            length: 255
        url:
            type: string
            length: 255
        description:
            type: string
            length: 500
            nullable: true
    lifecycleCallbacks: {  }
