fcbn_new_si_veg:
    resource: "@FcbnNewSIVegBundle/Resources/config/routing.yml"
    prefix:   /siveg

fcbn_new_si_flore:
    resource: "@FcbnNewSIFloreBundle/Resources/config/routing.yml"
    prefix:   /

si_flore:
    resource: "@SIFloreBundle/Resources/config/routing.yml"
    prefix:   /siflore

fcbn_dashboard:
    resource: "@FcbnDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /fos

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
 
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password 

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

