security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_MENU_ADMIN]
        SONATA_USER_ADMIN_USER:
            - ROLE_SONATA_USER_ADMIN_USER_EDIT
            - ROLE_SONATA_USER_ADMIN_USER_LIST
            - ROLE_SONATA_USER_ADMIN_USER_CREATE
            - ROLE_SONATA_USER_ADMIN_USER_VIEW
            - ROLE_SONATA_USER_ADMIN_USER_DELETE
            - ROLE_SONATA_USER_ADMIN_USER_EXPORT
            - ROLE_SONATA_USER_ADMIN_USER_OPERATOR
            - ROLE_SONATA_USER_ADMIN_USER_MASTER
        SONATA_USER_ADMIN_GROUP:
            - ROLE_SONATA_USER_ADMIN_GROUP_EDIT
            - ROLE_SONATA_USER_ADMIN_GROUP_LIST
            - ROLE_SONATA_USER_ADMIN_GROUP_CREATE
            - ROLE_SONATA_USER_ADMIN_GROUP_VIEW
            - ROLE_SONATA_USER_ADMIN_GROUP_DELETE
            - ROLE_SONATA_USER_ADMIN_GROUP_EXPORT
            - ROLE_SONATA_USER_ADMIN_GROUP_OPERATOR
            - ROLE_SONATA_USER_ADMIN_GROUP_MASTER
        ROLE_SONATA_USER_ADMIN_USER_LIST:
            - ROLE_MENU_ADMIN
        ROLE_SONATA_USER_ADMIN_GROUP_LIST:
            - ROLE_MENU_ADMIN
#        SONATA:
#            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented


    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # This part is handled by the FOS User Bundle

        main:
            pattern:             ^/
            anonymous: ~
            context:             user
            form_login:
                provider:        fos_userbundle
                login_path:      sonata_user_admin_security_login
                use_forward:     false
                check_path:      /login_check
                failure_path:    null
                #success_handler: application_sonata_user.component.authentication.handler.login_success_handler
            logout: 
                path:            /logout
                #success_handler: application_sonata_user.component.authentication.handler.logout_success_handler

    access_control:
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
         - { path: ^/query , role: IS_AUTHENTICATED_ANONYMOUSLY}
         - { path: ^/dashboard/sendemail, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/$ , role: IS_AUTHENTICATED_ANONYMOUSLY}
         - { path: ^/ , role: IS_AUTHENTICATED_FULLY}
#    acl:
#        connection: default

