<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    public function __construct()
    {
        parent::__construct();
        $this->enabled = true;
    }
    protected $id;
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns a string representation
     *
     * @return string
     */
    public function __toString()
    {
        $tmp = array();
        if ($this->getFirstname()) {
            $tmp[] = $this->getFirstname();
        }
        if ($this->getLastname()) {
            $tmp[] = $this->getLastname();
        }
        $user_string = $this->getUsername() ? : '-';
        if (count($tmp)) {
            $user_string = implode(' ', $tmp);
        }
        return $user_string;
    }
}
